<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickCart.Ordering.Application\QuickCart.Ordering.Application.csproj" />
    <ProjectReference Include="..\QuickCart.Ordering.Domain\QuickCart.Ordering.Domain.csproj" />
  </ItemGroup>

</Project>
